FUNCTION-POOL ZSMW0_SHTM MESSAGE-ID W3 NO STANDARD PAGE HEADING.

TABLES: WWWDATA, WWWPARAMS, MIMETYPES.

DATA  HTML LIKE W3HTML OCCURS 100 WITH HEADER LINE.
DATA  MIME LIKE W3MIME OCCURS 100 WITH HEADER LINE.
DATA:  OBJDATA LIKE WWWDATATAB,
       OBJID   LIKE WWWDATAID.
DATA  SUBRC TYPE I.

DATA  D_MIMETYPE LIKE W3PARAM-CONT_TYPE.
DATA: D_APPLICATION LIKE W3FILE-NAME,
      FILENAME      LIKE RLGRAP-FILENAME.

CONSTANTS: C_FILENAME    LIKE WWWPARAMS-NAME  VALUE 'filename',
           C_FILESIZE    LIKE WWWPARAMS-NAME  VALUE 'filesize',
           C_MIMETYPE    LIKE WWWPARAMS-NAME  VALUE 'mimetype',
           C_CHECKOUTDIR LIKE WWWPARAMS-NAME  VALUE 'checkoutdir',
           C_EXTENSION   LIKE WWWPARAMS-NAME  VALUE 'fileextension',
           C_UPLOAD      LIKE WWWDATA-OBJID   VALUE 'upload',
           C_DOWNLOAD    LIKE WWWDATA-OBJID   VALUE 'download',
           C_MIMEAPPL    LIKE WWWDATA-OBJID   VALUE 'mimeappl',
*** fuer ITS
           C_HOSTNAME    LIKE WWWPARAMS-NAME  VALUE 'hostname',
           C_LONGNAME    LIKE WWWPARAMS-NAME  VALUE 'longname'.

* screen 200
  CONTROLS: WWWPARAMS_CONTROL TYPE TABLEVIEW USING SCREEN 200.

  DATA WWWPARAMS_CHECK.
  DATA WWWPARAMS_TAB LIKE WWWPARAMS OCCURS 10 WITH HEADER LINE.
  DATA WWWPARAMS_SEL LIKE WWWPARAMS.
  DATA WWWPARAMS_NEW LIKE WWWPARAMS.
  DATA PARAMS_SELECTED TYPE I.

* screen 210
  DATA: G_ANSWER.                       "Antwortfeld
  DATA: OBJECT_TYPE(4).
  DATA: STATUS_CREATE.

DEFINE ONE_SCREEN_BACK.
  SET SCREEN 0.
  LEAVE SCREEN.
END-OF-DEFINITION.

* INCLUDE LZSMW0_SHTMD...                    " Local class definition
